import styles from "./reprise.module.css";

export default function Reprise() {
    return <article>
        <header>
            <h1>
                <img className={styles.light} width="75" height="75" src="/img/logos/reprise-light.png" />
                <img className={styles.dark} width="75" height="75" src="/img/logos/reprise-dark.png" />
                Reprise
            </h1>
            <p>Published <time datetime="2025-08-10">Sunday, August 10,
            2025</time>.</p>
        </header>

        <p>As a lifelong student of the guitar, I need good systems to keep my
        practice on track. This is the story of how I built Reprise, an app to
        help me manage my practice sessions.
        </p>

        <p> At first, Reprise was simply a notepad and a pen. I made a grid
        on a piece of paper. Down the left side of the grid I made a list of
        the exercises I would practice. In the cell to the right of the
        exercise names I recorded the current tempo for it.</p>

        <p> During a practice session, I would go down the list of exercises.
        For each one I would set the metronome speed on the metronome app
        in my phone, play the exercise, update the speed on my sheet if needed,
        and then move to the next exercise until I was done. </p>

        <p> This was a fine workflow, but there were a few annoying things
        about it. One is that before each exercise, I had to adjust the
        metronome app I was using. I wanted something more like a playlist of
        exercises, where all I had to do was tap "next" and I would be on to
        the next tempo. </p>

        <p> So I started building something that could beat my pen-and-paper
        system. Some of the early versions of this app were built into this
        website. The results of this work are still there: </p>

        <ul>
            <li><a href="/metronome">A metronome</a></li>
            <li><a href="/note-trainer">A note trainer</a></li>
            <li><a href="/practice">A practice routine and exersize tracker</a></li>
        </ul>

        <p>
        Feel free to use them if you want. They are good prototypes, but they
        don't work very well on mobile. To make something reliable enough
        to use as a daily practice tool, I decided to make an app. The biggest
        thing I got from this was a reliable way to play audio (required for 
        a good metronome).</p>

        <h2>Introducing Reprise</h2>

        <div id={styles.repriseScreenshot}>
            <img className={styles.light} width="350" height="auto"
                src="/img/reprise/1_basic_usage_light.png"
                alt="A screenshot of Reprise" />
            <img className={styles.dark} width="350" height="auto"
                src="/img/reprise/1_basic_usage_dark.png"
                alt="A screenshot of Reprise" />
        </div>

        <p>Reprise allows you to easily maintain a your practice routine. When
        it's time to practice, Reprise will guide you through your session.
        Features include:</p>

        <ul>
            <li><strong>Custom practice routines:</strong> Create
            multi-exercise routines and assign a specific tempo to each 
            exercise.</li>
            <li><strong>Tempo Recall:</strong> The app remembers the last tempo
            used for each exercise so you can pick up right where you left
            off.</li>
            <li><strong>Randomized note drills:</strong> Practice finding notes
            with autogenerated prompts to build familiarity and quick recall.</li>
            <li><strong>Timed practice mode:</strong> Set a duration and tempo
            for focused, time-boxed sessions (perfect for warm-ups or short
            drills).</li>
            <li><strong>Save & resume:</strong> Persist your routines and
            settings so your practice flow stays uninterrupted across
            sessions. Also it's private: all data is saved on your local device
            only.</li>
            <li><strong>Clean, distraction-free interface:</strong> A simple UI
            that keeps the focus on practicing efficiently. No ads!</li>
        </ul>

        <p>In this state, it's pretty good for my needs, but there's definitely
        room to improve. Here are some features I think would be great to
        have in the future:</p>

        <ul>
          <li><strong>Android app:</strong> If there's interest, I could do an
          Android app as well.</li>
          <li><strong>Sharing routines and exercises:</strong> Send your custom
          routines or drills to friends, students, or bandmates.</li>
          <li><strong>Cross-device syncing:</strong> Keep your routines,
          exercises, and settings in sync across all your devices.</li>
          <li><strong>Practice history mode:</strong> View your progress over
          time with graphs and visual insights.</li>
          <li><strong>Advanced routine management:</strong> Easily move or copy
          exercises between routines for better organization.</li>
        </ul>
    </article>;
}
